### ISSUE TITLE
Log out button does not log me out of Carbon

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#1]
Domain(s): carbon.meshify.com, hsb-carbon.meshify.com
Reproduction steps: 
1. Log in as a user
2. Click log out
Current Results: Page directs to "Authenticate" page instead of logging out
Expected Results: Should end the session and log the user out.

**Comment by Ashtonian** [comment]
If I understand this correctly I think this is an issue with chrome not respecting the set-cookie header to modify a cookie unless you send the cookie in with the request to be modified. I think this fixes it for admin which can be replicated for the dashboard. Submitted https://github.com/meshifyiot/applications/pull/40 for @MattMadeiro review. 

also updated the api/logout behavior to reference original cookie values and return 404 if there is no cookie found. See https://github.com/meshifyiot/carbon/pull/227 

Related issue: https://github.com/github/fetch/issues/386

**Comment by Ashtonian** [comment]
@psk788 should be deployed for admin

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/27/17.

@psk788 @willpopski, please test this for us. As of time of writing, I'm able to log out both from admin and dashboard. Dashboard has a bug wherein it breaks if you immediately then log back in — to circumvent this, after logging out, refresh the page once. I'll get the bug fixed this week.

**Comment by psk788** [comment]
@MattMadeiro Logout appears to work correctly now.  Do you want me close this ticket now or leave it open until you take care of the dashboard bug?

**Comment by MattMadeiro** [comment]
We'll go ahead and close it. The dashboard bug will be fixed soon as we start rewriting the dashboard core.
