### ISSUE TITLE
Feature Request: Condition field a wrapped large text field

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#100]
Current Behavior: Condition field is a standard sized text field that only displays a certain amount of characters before scrolling offscreen.

Requested Behavior: Have the Condition be a large text field that wraps the text so the entire condition can be seen at once if it's a longer rule.

![image](https://user-images.githubusercontent.com/9382834/32789847-ca1276de-c92a-11e7-9448-1df901ff9372.png)

**Comment by NateDawg90** [comment]
Merged and deployed on 11/16/17
