### ISSUE TITLE
Feature: Ability to verify phone number with the Carbon API

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#101]
On HSB's Enrollment core, when a user is created, we'd like to verify that the entered phone number is an existing one. 

Using Twilio API requests to verify the number on the front-end is something we'd like to avoid, because then we'd have the key and secret in the source code.

Ideally, I could make a request to a Carbon API endpoint with the phone number and the verification would happen in the background.

**Comment by willpopski** [comment]
@decker405 Can we get a response to this? The project team needs to decide whether or not HSB will implement this using a Meshify API or outside of Meshify.

**Comment by decker405** [comment]
We're not going to implement this at the current time. This would best be implemented outside of Meshify.

**Comment by willpopski** [comment]
This is a firm HSB requirement. If it is implemented outside of Meshify, there would need to be an entirely new authorization system, which doesn't make any sense. More specifically, the requirement is that the HSB user's authenticated session to be able to make these requests.

It is also a general need and not specific to a single customer.

I'd recommend we include rate limiting at the user level. They would need something like 100 per month.

**Comment by Ashtonian** [comment]
this was deployed, we may move this endpoint/change it later but for now this will work. See http://carbon-docs.meshify.com/#!/Experimental/Experimental_fetch_phone_info 

The endpoint will return 404 if the number is bad or not found.

NOTE: This is just a passthrough from the user's phone service provider. Ours is twilio see example response below. For on prem installs this will be different. Also please note each request is $0.005.  

```javascript
{
    "caller_name": null,
    "country_code": "US",
    "phone_number": "+11234567890",
    "national_format": "(123) 456-7890",
    "carrier": {
        "mobile_country_code": "310",
        "mobile_network_code": "150",
        "name": "AT&T Wireless",
        "type": "mobile",
        "error_code": null
    },
    "add_ons": null,
    "url": "https://lookups.twilio.com/v1/PhoneNumbers/+11234567890?Type=carrier"
}
```

**Comment by balintd** [comment]
Thank you!
