### ISSUE TITLE
Critical: Messages not being posted to Carbon

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#102]
Messages are flowing properly through Node Red and I can see them pass through MQTT Lens but Carbon is not reflecting the updated values.

The same happens if I try to post a topic via MQTT Lens.

![image](https://user-images.githubusercontent.com/9382834/32800282-e38405de-c947-11e7-90f5-65952a18298d.png)
![image](https://user-images.githubusercontent.com/9382834/32800306-f3bc57da-c947-11e7-9b77-e2d3fb075f43.png)

**Comment by MattMadeiro** [comment]
We're investigating. Thanks for the heads up!

**Comment by Ashtonian** [comment]
restarting ingestor fixes it, reviewing further.

**Comment by willpopski** [comment]
How much down time?

**Comment by psk788** [comment]
Messages are flowing through now.  What was the issue (and how can we prevent in prod)?

**Comment by Ashtonian** [comment]
Production service was intermittent from 12PM to 2:30PM.

**Comment by willpopski** [comment]
@psk788 I can't speak for future product, but I'll add this to my monitoring app, so at least we'll know faster.

**Comment by psk788** [comment]
Traffic appears to have stopped again around 5:45PM EST on 11/14/2017

**Comment by willpopski** [comment]
You can see node status here:

https://carbon.meshify.com/dashboard/#/folder/4122
