### ISSUE TITLE
Authorize button missing from carbon-docs.meshify.com

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#103]
This button allows the user to test the API from within the browser. It is not in the Carbon Docs api site per screenshot.

![image](https://user-images.githubusercontent.com/116724/32815955-1c349874-c97c-11e7-8037-ff961c9cb4c3.png)

**Comment by decker405** [comment]
We took it out because we couldn't get it to work correctly.

**Comment by willpopski** [comment]
Then shouldn’t we remove the “try it out” buttons and the domain text box? I’ve gotten customer complaints on this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
