### ISSUE TITLE
Adding new domain through Admin causes 'Domain not allowed' error

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#104]
Domain: https://hsb-test-carbon.meshify.com/admin#domains/edit/35

I added the domain, after trying to visit, I received an error saying: 

```
Sorry, An Error Has Occured

Domain 'hsb-test-carbon-setsag.meshify.com' not allowed.

Contact with support team.
```

**Comment by balintd** [comment]
I deleted the domain I mentioned in the issue above and recreated it (had a typo in the first one)

'hsb-test-carbon-setseg.meshify.com'

https://hsb-test-carbon.meshify.com/admin#domains/edit/39

However I'm still getting the same error.

**Comment by decker405** [comment]
The domain needs to read: `hsb-test-setsef.carbon.meshify.com` to have DNS and HTTPS automatically work.

**Comment by balintd** [comment]
Ah, ok, thanks!
