### ISSUE TITLE
Cron Rules Seem to be broken

### ISSUE THREAD

**Issue by JonIsaiah** [meshifyiot/carbon-docs#107]
Chron Rules not Running

Domain: nov.meshify.com

To Reproduce:  save a simple rule on a chron timer, the icon status of the node does not change

Affected Node Type:  novpump (and probably all others)
Affected id: 0303030303030303
Affected Rule Id: 114 Level Not Updated
Affected Channel:  mono_sense_level

Expected Behavior:  Rule changes status icon on time interval

Notes:  API reflects changes in rule successfully.  Rule is actually evaluating true, just does not appear to be running on chron

**Comment by Ashtonian** [comment]
initial issue was an issue with the sql to trigger cron jobs fixed with https://github.com/meshifyiot/carbon/commit/57d1cf142498cb9771af0c61f6d7711b70a17cad. 

also had to update env variables but it should work now...
