### ISSUE TITLE
Need help with mf-chart (lines not appearing but confirmed data is loading)

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#108]
Working on a carbon template to display some internal data. I've confirmed that there is data within the time range (and that it is loading via API), but data isn't being displayed on the chart (no line). The labels work.

I copied the example from documentation on carbon-docs as well as cross referenced with other charts. Any thoughts?

```
<mf-chart start_time={ moment().subtract(7, 'days').format() }
   channels="pipeline-delay-legacy,pipeline-delay-carbon" label="Pipeline Delay" />
```

Logged in as support@meshify.com. Feel free and edit this template if you need to test anything out.
https://carbon.meshify.com/dashboard/#/folder/4122/node/8567

![image](https://user-images.githubusercontent.com/116724/32868577-9ab94444-ca38-11e7-8ace-52366f4d75f2.png)

**Comment by NateDawg90** [comment]
Fixed and Deployed on 11/16/17
