### ISSUE TITLE
Meshify default logo not loading on dashboard

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#109]
Domain: hsb-test-carbon.meshify.com
Current Behavior: Dashboard is getting an error trying to find the default logo
Expected Behavior: If no theme is specified, put the Meshify logo in the corner
![image](https://user-images.githubusercontent.com/9382834/32954360-e02f1370-cb80-11e7-821f-3654368c44d5.png)

**Comment by MattMadeiro** [comment]
Fixed and deployed on 11/17/17. 

Thanks for the catch!
