### ISSUE TITLE
How do you use files?

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#11]
How do I use files that are uploaded through the API?

**Comment by decker405** [comment]
This is waiting on meshifyiot/carbon#255 and will then be documented.

**Comment by decker405** [comment]
Documented.

**Comment by willpopski** [comment]
How are they used in templates? Do you want people to hit the API every time an image is used? Or would you want the ability to directly get from the (public) url?

**Comment by willpopski** [comment]
The documentation doesn't address that question.

https://github.com/meshifyiot/carbon-docs/tree/master/cms#files

**Comment by decker405** [comment]
You can link directly to a file by its name. `https://carbon.meshify.com/api/files/public/somefile.txt`

Matt is adding a UI element that shows you the full link today.

**Comment by MattMadeiro** [comment]
UI element is added and deployed. When you click on a file in the file list and the text input for the filename appears, the full path to the file will appear underneath it.
