### ISSUE TITLE
Domain created in admin core doesn't seem to receive theme

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#115]
Here is the domain I've created through the admin core:

https://hsb-test-carbon.meshify.com/admin#domains/edit/39

When I visit hsb-test-setseg.carbon.meshify.com/enrollment it's not getting the theme object, even though it has one. I went through the same process when I attached a theme to this domain for example https://hsb-test-carbon-cmic.meshify.com/enrollment, it works there.

**Comment by MattMadeiro** [comment]
I went to http://hsb-test-setseg.carbon.meshify.com/enrollment and /dashboard, and in both cases the window.Theme object had the theme information. Can you clarify what you're seeing?

**Comment by balintd** [comment]
Hm, it's working now. Might needed some time to show up. I'll close this, thanks!
