### ISSUE TITLE
Parent Folder in the edit folder menu is a dropdown instead of the combobox

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#116]
Can parent folder be a searchable list like the other select lists in the admin tab? It's hard to find parent folders as it is unsorted.

![image](https://user-images.githubusercontent.com/9382834/33077893-05cc104e-ce9f-11e7-9005-4e36ab552351.png)

**Comment by MattMadeiro** [comment]
Fixed and deployed on 11/27/17.
