### ISSUE TITLE
Dashboard: Current User information is not in scope

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#119]
Current Behavior: In the dashboard I have no idea who I am.  So if i'm impersonating, I don't know who I'm impersonating.

Requested Behavior:  Near the log out, it should display the email of the logged in user (like the admin).  Also could we have the current user in the context somewhere so that if I wanted to refer to that user name, I could.

![image](https://user-images.githubusercontent.com/9382834/33080893-220a9b42-cea7-11e7-9623-d528cb5d1f64.png)

**Comment by NateDawg90** [comment]
Fixed and deployed on 12/12/17

**Comment by willpopski** [comment]
@NateDawg90 just tested this and don't see the user name on the top bar. I did a hard reload and disabled cache. Does anybody else see the username appearing?

**Comment by NateDawg90** [comment]
@willpopski  In dashboard, you should see your user email in grey next to the Log Out button. Does your user have an email address?

**Comment by decker405** [comment]
I just deployed it this morning.
