### ISSUE TITLE
Root user cannot modify root folder

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#120]
Current Behavior: Nobody, regardless of root access can modify the top most folder despite having full read/write access in the app.

Expected Behavior: Users marked isRoot should be able to modify any folder regardless.

Business Rationale: I need to rename the folder from "HSBTest" to "Hartford Steam Boiler" or add theme information that the whole app might need to reflect.

**Comment by MattMadeiro** [comment]
Verified — we're getting a 403 Forbidden from the API.

**Comment by Ashtonian** [comment]
this has been deployed, you must be a root user to modify it. You can change everything except the PID.
