### ISSUE TITLE
Dashboard: Nodetype template position not always working

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#122]
Domain: hsb-test-carbon.meshify.com

Current Behavior: I have a template with position 100 which is the highest position but it's being shown in the middle of the other templates.

Expected Behavior: It should sort on position. With higher position numbers being further to the right.

![image](https://user-images.githubusercontent.com/9382834/33083439-60eac368-cead-11e7-80f4-688c514a5527.png)

**Comment by MattMadeiro** [comment]
Fixed and deployed on 11/21/17.
