### ISSUE TITLE
Important: After editing folder metadata on Admin, some already existing metadata properties and values disappear

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#123]
Example folder: https://hsb-test-carbon.meshify.com/admin#folders/edit/4486

The folder was created with these metadata properties and values:
![folder1](https://user-images.githubusercontent.com/368531/33089452-e765229c-cef0-11e7-97e0-5f93fd6816c4.jpg)

After editing one of the metadata values on Admin and saving, some of them disappeared:
![folder2](https://user-images.githubusercontent.com/368531/33089464-f414c0c4-cef0-11e7-80b6-1074383b3a4e.jpg)

Data seems to be missing not just from UI, but also when requested from the API.

**Comment by MattMadeiro** [comment]
Seems like our JSON editor is leaving out any pairs that have a key, but not a value. We'll get it fixed. Thanks for the heads up.

**Comment by NateDawg90** [comment]
This issue will be fixed by the smart json editor when it is merged.

**Comment by NateDawg90** [comment]
Fixed and deployed on 12/6/17

**Comment by willpopski** [comment]
Thanks for the fix!
