### ISSUE TITLE
Failure to add a new template 

### ISSUE THREAD

**Issue by Jmatos87** [meshifyiot/carbon-docs#124]
Domain: carbon.meshify.com

I created a node type template which can be seen here: 

![image](https://user-images.githubusercontent.com/16376264/33094683-9c1b9714-cec6-11e7-8beb-b9b527fc04fd.png)

Then I attached the template to a type called test-node (unique id === abc123) . On the dashboard, I click on the unique id abc123 and I expect to see the created template but instead I see: 

No templates available.

**Comment by MattMadeiro** [comment]
Try something for me real quick — change the template name to something other than 'details' and see if that works for you. test-node-info or something like that.

**Comment by Jmatos87** [comment]
Works with test-node-info

**Comment by MattMadeiro** [comment]
Cool. I'll close this for now and create an internal ticket to resolve the 'details' part being problematic. Thanks for the catch!
