### ISSUE TITLE
"Forgot password" link does not appear on default login page

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#125]
When I go to [nov.meshify.com](https://nov.meshify.com), I don't have the option to use a password reset.

If I go to [nov.meshify.com/admin](https://nov.meshify.com/admin) then there is a link for password reset.

This is causing confusion with customers because usually 'admin' is generally NOT set as the default core, so customers have no way to enter the platform if they forgot their password (and don't happen to know about the URL).
***
Dashboard Core (What most users see)

![image](https://user-images.githubusercontent.com/116724/33099516-b9040766-ced6-11e7-9def-df60c6501765.png)
***
Admin Core

![image](https://user-images.githubusercontent.com/116724/33099461-8de28c74-ced6-11e7-9d82-97877c867d78.png)

**Comment by decker405** [comment]
Matt is adding this to the dashboard, and I am changing the server code to send users back to the application that they used the "Forgot Password" link from.

**Comment by MattMadeiro** [comment]
Fixed and deployed on 11/30/17.
