### ISSUE TITLE
Cannot Update Node Type - Alias Channel

### ISSUE THREAD

**Issue by Jmatos87** [meshifyiot/carbon-docs#127]
![image](https://user-images.githubusercontent.com/16376264/33140061-90dd02ee-cf74-11e7-848c-000bbbe02888.png)

Node type: parking-garage-counter

I get a failure to update whenever I try to change the second channel to a type alias:boolean. Which is odd because the first one worked fine yesterday. The error that pops up is:

not a valid type:  exit-event   alias:boolean

Desired functionality would be to change a normal channel into an alias channel. 
I have tried deleting the second channel and remaking it as an alias channel but that hasn't worked. 

Update: A node type that is attached to a node cannot be edited. Once there aren't any nodes attached to it, then it can be edited again. This behavior is consistent and limited to the parking-garage-counter node and the corresponding 2 node types. I tried this on the car-sensor but it updates just fine even with nodes attached.

**Comment by MattMadeiro** [comment]
UI is posting the channel schema correctly, so I think this is on the API side. @Ashtonian?

**Comment by decker405** [comment]
Fixed.
