### ISSUE TITLE
API requests option to use Unique Ids instead of Node Ids

### ISSUE THREAD

**Issue by Jmatos87** [meshifyiot/carbon-docs#128]
Matt P. and I were going through the API and thought it would be cool to have an option to utilize unique ids which are user created as opposed to the Node ids which are system generated and not intuitive. 

Concern: Collisions. 

Possible solution: Having a check for duplicate unique ids when a node is created or updated.

**Comment by decker405** [comment]
Closing in favor of duplicate issue #114
