### ISSUE TITLE
Feature: Folder name available in email templates

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#129]
In HSB's Enrollment UI project, they'd like to include account names (name of the folder the created user is in) in the user invite emails.

**Comment by Ashtonian** [comment]
This is not deployed yet.

Users can be in multiple folders so we attached all the users folders to the context object. 

Example Template usage: 
```django
{{ Folders.0.Name }} 
```
or 
```django
{% with Folders|first as firstFolder %}
    {{ firstFolder.Name }}
{% endwith %}
```

**Comment by Ashtonian** [comment]
@balintd this has been deployed, let me know if there is any issue.
