### ISSUE TITLE
Feature: Ability to customize email subjects and from email for user invite and password reset emails

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#130]

**Comment by decker405** [comment]
@balintd: we're looking into this today and tomorrow. We will provide an expected timeline by Friday.

**Comment by balintd** [comment]
Thanks!

**Comment by decker405** [comment]
This will be in the next 2 week sprint starting Monday.

**Comment by Gayle313** [comment]
May I have a status on this?

**Comment by Ashtonian** [comment]
this has been deployed
