### ISSUE TITLE
Internal Server Error on request to '/api/data/current'

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#131]
On opening this node template I receive the internal server error:

https://carbon.meshify.com/dashboard#/folder/1/node/8566

`bundle.min.js:288 GET https://carbon.meshify.com/api/data/current?nodeId=8566&nodeId=8571&nodeId=9734&nodeId=9735&nodeId=9736 500 ()`

Here is the response for the same request in Postman

```
{"id":"ba9Cbjtt","code":"internal","status":500,"detail":"Internal Server Error [jfMjdsEL5E-513537]"}
```

Request to a single node is working, it seems that only requests for multiple node's data result in this error. In the last 15 minutes this request worked a couple times looking at the page above, but results in the error most of the time.

**Comment by decker405** [comment]
Working on it.

**Comment by decker405** [comment]
Fixed. This change causes invalid date values to be replaced by default values. It also prevents any invalid date ranges from entering the system.

**Comment by balintd** [comment]
Thank you!
