### ISSUE TITLE
Failure to receive email from a rule trigger

### ISSUE THREAD

**Issue by Jmatos87** [meshifyiot/carbon-docs#133]
The name of the Reaction and Rule is called "Parking Full". Both are active. The Notification Schema has been created with a default schedule. I subscribed to it. The logic for the rule is for the notification to be sent off if the parking counter >=5. The rule conditions have been met many times but still no email. 

Rule Id: 139
Reaction Id: 172
Channel name: parking-counter
User Id: 1330

**Comment by MattMadeiro** [comment]
For that particular Reaction, I see that the Reaction type is 'sms', not email. Is that the issue?

**Comment by Jmatos87** [comment]
Sorry about that. I had added my phone number to my account to see if that would work but that hasn't worked either. Just changed it back to email and that isn't going through still.

**Comment by MattMadeiro** [comment]
Closing this for now, as we have an internal ticket to address issues with hyphens/dashes.
