### ISSUE TITLE
Issue with theme attached to domain on tenant 316

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#134]
I attached a theme for this domain https://test-setsegschools.carbon.meshify.com/ When visiting the the enrollment core at https://test-setsegschools.carbon.meshify.com/enrollment, theme is not being received, instead I get a 401 `bad credential` error on the request to `api/theme`

Previously I attached the same theme for other domains on the 100k tenant, they do receive it still (example: https://setsegschools.carbon.meshify.com/enrollment). Seems to be an issue specific to the tenant, but all settings look good from admin and the enrollment core code is the same,

**Comment by Ashtonian** [comment]
`api/theme` is for the user's theme object based on the folder they are in. This is not accessible until the user is logged in as it is their own theme object. Which is why you received a 401. The application/core and domain theme are  baked into the index.html. See [link](https://github.com/meshifyiot/applications/blob/67409cb8676c5bd5cf3feb5cdadda0d47e86835c/cores/enrollment/index.html#L20).

**Comment by balintd** [comment]
Yeah, I shouldn't have mixed the `api/theme` request here since I was checking the site logged out. 

However the theme was uploaded to the domain and it didn't load when visiting the domain (and it did on another tenant for another domain that had the same theme. I checked it again now and it started working in the meantime. Not sure what fixed it, but it's ok now.

**Comment by Ashtonian** [comment]
this code block renders the theme json into window.theme when index.html is loaded and needs to present to access it off the window. There is also a bug related to the theme not being updated if it changes but that will be resolved today.


https://github.com/meshifyiot/applications/blob/hsb-enrollment/cores/enrollment/index.html#L18 
```html
  <script>
    window.BasePath = "{{ BasePath }}";
    window.Theme = {{ ThemeJSON | safe }};
  </script>
```

**Comment by balintd** [comment]
Ok, I think that might have been because of the bug you mentioned. Both tenants have the same version of the `enrollment` core and both handle themes like your example above.
