### ISSUE TITLE
Error When Trying to Rename Folders 

### ISSUE THREAD

**Issue by JRhynsburger** [meshifyiot/carbon-docs#135]
Occurring on https://support.carbon.meshify.com/admin#folders
Error "Unable to Save Folder. Try Again Later."

To Repro:
- Go to https://support.carbon.meshify.com/admin#users
- Click on "Folders"
- Choose a folder
- Edit the name and click on "Save"
-Error message will appear

**Comment by MattMadeiro** [comment]
Hi Jaime,

I'm unable to reproduce this. Which user account are you logged in as when you see that error?

**Comment by JRhynsburger** [comment]
Using Support Account (Root access)

**Comment by MattMadeiro** [comment]
I only see the error here:

https://support.carbon.meshify.com/admin#folders/edit/1921

That's for the folder currently named 'HSBTest,' which is the root folder on the account. Logged in as a root user, I _think_ you should be able to edit it, but the API is returning 403 forbidden, so I'll have to defer to @Ashtonian and @decker405.

**Comment by decker405** [comment]
This is related to #120

**Comment by MattMadeiro** [comment]
Good call. We'll close this issue for now, as it's a duplicate. @JRhynsburger, please keep tabs on #120 for updates.
