### ISSUE TITLE
Chart not displaying on M1 template in dashboard

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#138]
I'm working on migrating the Charts M1 template to carbon and I've ran into this issue.

URL: https://carbon.meshify.com/dashboard#/folder/1/node/8566 `Data from Protocol` section.

Here is the code I'm using to generate the charts:
```
<div each={ chart in history.charts } class='w-50 fl' style='border: 1px solid #ddd; padding: 1em 15px; border-left: none; border-top: none;'>
  <mf-chart channels={ chart } height={ 300 } start_time={ moment().subtract(1, 'days').format() }>
</div>
```

Value of `history.charts`:
```
0:{name: "2-2-v", label: "Current", unit: "amp"}
1:{name: "2-3-v", label: "Number of Starts", unit: " starts"}
2:{name: "2-4-v", label: "Motor Current", unit: "Amps"}
3:{name: "2-5-v", label: "Motor Current Trip", unit: "Amps"}
4:{name: "2-7-v", label: "Current State", unit: ""}
5:{name: "2-8-v", label: "Last Event", unit: ""}
```
Channels above have values as well.

I'm not sure if it's a bug or there is something I should be doing differently, this data structure I'm passing to the mg-chart tag seems to work elsewhere.

**Comment by MattMadeiro** [comment]
Check the docs for the mf-chart: https://github.com/meshifyiot/carbon-docs/blob/master/cms/templates/line-chart.md

If you try to pass in channels in the way you're doing it, you have to pass them in as a comma-separated string of channel names. An array of JSON objects can only be passed in as part of a larger chart settings configuration block.

**Comment by balintd** [comment]
Ah, I understand now, thanks!
