### ISSUE TITLE
Reboot Functionality for DEALER Role

### ISSUE THREAD

**Issue by JRhynsburger** [meshifyiot/carbon-docs#139]
FEATURE REQUEST from user: Kevin Johnson of Mistaway

"We need the give users with the DEALER role the ability to reboot gateways from the web app. Please advise. Right now this ability is reserved for users with ADMIN role."
RE: Ticket #965

**Comment by decker405** [comment]
This is a legacy issue, it should not be on the Carbon bug repo.
