### ISSUE TITLE
Chart is rendering, but doesn't show line for values on M1 Carbon template

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#140]
This is a seperate issue for the same M1 template.

URL: https://carbon.meshify.com/dashboard#/folder/1/node/8566 `Data from Protocol` section.

Here is the code I'm using to generate the charts:
```
<div each={ chart in history.charts } class='w-50 fl' style='border: 1px solid #ddd; padding: 1em 15px; border-left: none; border-top: none;'>
  <mf-chart channels={ chart.name } height={ 300 } start_time={ moment().subtract(1, 'days').format() }>
</div>
```

Value of `history.charts`:
```
0:{name: "2-2-v", label: "Current", unit: "amp"}
1:{name: "2-3-v", label: "Number of Starts", unit: " starts"}
2:{name: "2-4-v", label: "Motor Current", unit: "Amps"}
3:{name: "2-5-v", label: "Motor Current Trip", unit: "Amps"}
4:{name: "2-7-v", label: "Current State", unit: ""}
5:{name: "2-8-v", label: "Last Event", unit: ""}
```
Channels above seems to have integer values, but the chart looks like before when I sent string values with sets and the values didn't get converted to numbers.

In the channels data (history.allChannels variable) it seems that the values are numbers not strings, so that may not be the issue, just an observation

**Comment by MattMadeiro** [comment]
The chart is working as expected. In this case, when you're querying the history endpoints for those channels, they all have a single value in their history, a data point from November 24th. Your chart, however, is setting the start time to 1 day ago, so the API returns an empty array of datapoints.

**Comment by MattMadeiro** [comment]
(For future debugging, remember to check the result of the History API calls in the Network tab in Chrome's Developer Tools.)

**Comment by willpopski** [comment]
Probably worth noting, that showing a blank chart has confused a lot of people. @balintd, maybe we can explore adding some text saying "no data found from [start date] to [end date]. If you want to do a pull request for the mf-chart tag, that is fine.

**Comment by balintd** [comment]
I assumed the date range buttons work and clicking `All` should show some values regardless of start time. Good point about checking API response, I'll make sure to do that next time. I also created a new pull request for a message that shows up if there is no data from specified or default start time.

Thanks!
