### ISSUE TITLE
Dashboard not pulling theme from folders

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#141]
Domain: hsb-test-carbon.com
Expected behavior:  If I add a theme to a parent folder, I should be able to access that theme and any parent folder theme from any node in that folder.

Actual behavior: I can only see theme attributes from the domain/application.

Business rationale: In HSB, the device locations are stored in a theme attribute and can be different based on HSB clients.  If I'm a user that has access to multiple customers (admin or MSC) then I'm not using the client specific domain to log in then the client specific theme information does not display.  Having folder level theming in the dashboard would also be useful for repurposing the same node types across clients while giving them custom looks and behaviors.

**Comment by Ashtonian** [comment]
the UI will need to be updated to pull from `api/theme` after login and merge the result with the theme object.

**Comment by decker405** [comment]
Fixed and deployed.
