### ISSUE TITLE
When opening a rule, the page is focused in the middle instead of the top

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#144]
Current behavior: Open a rule, and page loads with focus on middle of page
Expected behavior: Should be at the top of the page so you don't have to scroll up (to edit rule name and such)

![image](https://user-images.githubusercontent.com/9382834/33773572-5bed6738-dc06-11e7-857b-1981f791a06d.png)

**Comment by decker405** [comment]
Fixed and deployed.
