### ISSUE TITLE
Feature: On reset password, type it twice and validate that the two match

### ISSUE THREAD

**Issue by shawegit** [meshifyiot/carbon-docs#149]
When setting the password, it would be helpful if a user who sets the password has to type it in twice. These should be compared and the new password should only be accepted if the two match. This would avoid accidently miss typing the password and not being able to login when typing it in "correctly".

**Comment by NateDawg90** [comment]
Merged and deployed.

**Comment by decker405** [comment]
Deployed from meshfyiot/applications#201
