### ISSUE TITLE
File Rename and Delete

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#15]
It would be helpful to be able to rename and delete files in the interface for:

- files
- cores

**Comment by NateDawg90** [comment]
Added and deployed on 10/3/17.

**Comment by willpopski** [comment]
Does this mean that core file upload will be re-added to the cores section of Admin?

**Comment by MattMadeiro** [comment]
The core file editor has been added back in, yeah.

Fixed and deployed on 10/4/17.
