### ISSUE TITLE
Charts feature: Add indicator on chart showing when rule is triggered

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#150]
This is probably an item for @Jmatos87, but wanted to put it on the backlog.

Using api/alarms/history on all rules for a given node, show the events on the chart as annotations:

https://api.highcharts.com/highstock/annotations

Question/challenge: How will we make text fit into small space. Can we use tooltip to show full alert?
Bonus: use rule severity color as annotation color.

![image](https://user-images.githubusercontent.com/116724/33953219-dde24dac-dff9-11e7-9aa1-4f97a2c20ee5.png)

**Comment by decker405** [comment]
Would you consider something like this instead (or also)? https://www.highcharts.com/stock/demo/yaxis-plotlines

**Comment by willpopski** [comment]
Yeah, those are great as well. In some cases, they serve a slightly different purpose.

There's a specific use case I have in mind. HSB has alerts that use dynamic thresholds based on multiple inputs or even rate of change.

But for many simple use cases, being able to parse rule triggers and automatically put the rule threshold on the chart would be an added bonus.

**Comment by NateDawg90** [comment]
merged and deployed.

**Comment by psk788** [comment]
Can you tag me when there's a document/example of this?  HSB just asked about a similar feature.
