### ISSUE TITLE
D3: Dashboard lags 5-10 seconds when displaying node templates in tenant with 7000 nodes

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#152]
Domain name: **test-support.carbon.meshify.com** (any domain with tenant 316) (presumably any tenant with thousands of nodes)

1. Log into dashboard 3 with support@meshify.com account. [link](https://test-support.carbon.meshify.com/dashboard3)
2. Click one of the nodes in alarm.
3. Wait for first template to render (~10 seconds).
4. Click on 'additional information' template tab.

Observed result: **Waiting for the next template to load causes the page to become non responsive and chrome to eventually present an kill tab modal.**

Expected result:
**If I am looking at a single node, I would not expect any delays or freezes in rendering the template, even if there are thousands of nodes in my visible scope.** The template works fine in other environments and doesn't have a large amount of data.

**Comment by decker405** [comment]
@willpopski That happens on both dashboard3 and dashboard. I can't tell what's happening, but it only happens with that Additional Info template.

**Comment by willpopski** [comment]
I'll modify this issue just to note that we still have performance issues when loading individual nodes templates in the high-node tenants. I suspect this will become a blocking issue in the Feb-March time frame.

**Comment by decker405** [comment]
@willpopski I'm suspecting this is a template and/or highcharts issue rather than a high node issue. What happens if you remove the broken information template?
