### ISSUE TITLE
Have Schema Scroll bar be more apparent in User Subscription page

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#156]
Current Behavior:  In the User Subscription page, it only shows 6 or so notification schemas at a time.  Because the scroll bar doesn't show up unless you try to scroll so there's no obvious way of knowing that this is the full list of schemas.  In the screenshot below, it shows 6 schemas when there are a total of 10 but I can't tell where the other 4 are.

Expected Behavior: Have the scroll bar always show up so users know that this isn't whole list.  Also consider adding a border.  Having only 6 with a hidden border just makes it look like the space is eating the schemas for no reason.

![image](https://user-images.githubusercontent.com/9382834/34529665-c5ba1304-f07a-11e7-8afa-0a3abceed2fc.png)

**Comment by decker405** [comment]
That's an OS X system level setting in System Preferences -> General :: Show scroll bars

**Comment by psk788** [comment]
Mac Rookie.  Thanks!
