### ISSUE TITLE
Admin core displaying incorrectly on IE11

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#157]
Example URL: https://test-setsegschools.carbon.meshify.com/admin

After opening the URL above, Admin core with login screen is displayed without issues on Chrome, but on IE11, it's only the Meshify logo that is displayed and nothing else. Screenshot below:

![image](https://user-images.githubusercontent.com/368531/34530885-cdde40ce-f0b0-11e7-98fe-4aa38266cf1d.png)

**Comment by decker405** [comment]
Fixed.
