### ISSUE TITLE
Users not being logged out correctly on IE11

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#158]
Example domain: https://test-setsegschools.carbon.meshify.com/enrollment

Steps to reproduce:
- Log in with User A in IE11 (https://test-setsegschools.carbon.meshify.com/enrollment#login)
- Click Logout in main menu
- Log in with User B
- Authentication goes through but User A is still logged in

This only seems to be happening in IE, works perfectly in Chrome.

**Comment by Ashtonian** [comment]
original ticket is still open https://github.com/meshifyiot/carbon-docs/issues/54

**Comment by balintd** [comment]
Sorry about that, for some reason I thought that was resolved already, thanks!
