### ISSUE TITLE
CSS in <style> tag inside node template Riot tag not working

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#161]
For example: carbon.meshify.com, m1-alerts template

```
<m1-alerts>
  <style>
    :scope .some-element{
      cursor: pointer;
    }
  </style>

  <div>
   ...
  </div>
</m1-alerts>
```

Tachyons classes don't cover changing icon to pointer while hovering over an element.

**Comment by balintd** [comment]
Inline styles seem to work.

**Comment by decker405** [comment]
@balintd: I believe the style tag needs to come at the end of everything inside of `<m1-alerts>`

**Comment by balintd** [comment]
The style tag can be at the top, that's where I put it in all my tags in the enrollment core for example. I just tried putting it to the buttom in the node template, that didn't work either.

**Comment by decker405** [comment]
Can you try something simple like:

```
.red {
   color: 'red'
}
```

I wonder if `:scope` doesn't work for some reason.

**Comment by balintd** [comment]
I tried that format already with

```
.w-100 {
   background-color:  red;
}
```

It didn't work either unfortunately.

**Comment by decker405** [comment]
It looks like the style tag either doesn't work with in browser compilation (which the NodeTypeTemplates require) or with the `<div data-is="tag-name">` format. This is either a Riot bug or "feature", I suggest we just stick with inline styles for now.

**Comment by decker405** [comment]
I'll add a note to document that `<style>` does not work in Node Type Templates.
