### ISSUE TITLE
D3 UI: Folder level alert rollups

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#163]
Add status icons to folders and show the highest severity level icon of contained folders or nodes.

**Comment by Gayle313** [comment]
Received a note from our PM that there may or may not be confusion on this request.    This originates from a request to be able to view any active alerts on folder.
 Folder View doesn't show any active alarms without drilling down into the account. Could we add "Alarms" to the "Inside" overview section? 
Hope this helps.  :)

**Comment by NateDawg90** [comment]
resolved and deployed
