### ISSUE TITLE
BUG:  Searching in Dashboard 3 is case sensitive

### ISSUE THREAD

**Issue by Gayle313** [meshifyiot/carbon-docs#164]
URL:  https://support.carbon.meshify.com/dashboard3#search
Search Functionality only works when using lower case letters.
See the attached screen shots for examples:

**Comment by Gayle313** [comment]
Adding screenshots
[#164 -Searching in Dashboard3.docx](https://github.com/meshifyiot/carbon-docs/files/1616660/164.-Searching.in.Dashboard3.docx)

**Comment by willpopski** [comment]
* Deleted the boilerplate text *

**Comment by Gayle313** [comment]
This is still an issue.
![image](https://user-images.githubusercontent.com/34075650/35400580-28fe8eb2-01c5-11e8-885b-767a9ce2b7e6.png)

**Comment by Gayle313** [comment]
This is still an issue
https://hsbdev.carbon.meshify.com/dashboard3#search
https://hsbqa.carbon.meshify.com/dashboard3#search

![case sensitive search](https://user-images.githubusercontent.com/34075650/36152417-f00bd882-10c2-11e8-8b03-d23cb0271bd2.jpg)

**Comment by NateDawg90** [comment]
Sorry, I hadn't deployed dashboard 3 yet. It should be up.
