### ISSUE TITLE
D3 UI: Default to "Node" tab view if there are no folders

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#165]
When browsing folder tree on Dashboard 3, as you descend a tree branch, you will inevitably hit a folder with no other folders--yet the (now empty) folder tab is still selected. It would be natural for the tab to switch to Nodes view when there are no folders.

Long term, @decker405 and I have discussed using Miller Columns to navigate through folders. They look like this:

![image](https://user-images.githubusercontent.com/116724/34743405-3972e57c-f54f-11e7-9cbe-d801b1c16d88.png)

**Comment by NateDawg90** [comment]
merged and deployed
