### ISSUE TITLE
Dashboard 3 - Add User Role as part of user tab

### ISSUE THREAD

**Issue by Gayle313** [meshifyiot/carbon-docs#166]
The User Role is not displayed when viewing users  in a folder.
URL: https://support.carbon.meshify.com/dashboard3#folders?folderId=4686
See attached screenshot.

**Comment by Gayle313** [comment]
adding attachment

**Comment by Gayle313** [comment]
[#166 - Add user role to user folder view.docx](https://github.com/meshifyiot/carbon-docs/files/1616741/166.-.Add.user.role.to.user.folder.view.docx)

added screenshot

**Comment by Gayle313** [comment]
Closed this issue in error.

**Comment by NateDawg90** [comment]
Fixed and deployed on 1/17/18
