### ISSUE TITLE
Dashboard3:  User View should match Admin User View.

### ISSUE THREAD

**Issue by Gayle313** [meshifyiot/carbon-docs#168]
URLs:
https://support.carbon.meshify.com/Admin#users
https://support.carbon.meshify.com/dashboard3#users

When using Dashboard3, the user view should match the Admin User View

**Comment by Gayle313** [comment]
Attempting to add an attachment.....have been unsuccessful.

**Comment by NateDawg90** [comment]
What specifically would you like added to the users screen to match the admin users screen?

**Comment by Gayle313** [comment]
![image](https://user-images.githubusercontent.com/34075650/35102411-e83f0850-fc30-11e7-8de3-2313a755017d.png)
