### ISSUE TITLE
Websocket connection causing error in IE11

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#171]
Screenshot of error: 
![image](https://user-images.githubusercontent.com/368531/35108317-8a45e7ee-fc73-11e7-9e8d-7d48eb7fa04d.png)

Code:
```
app.sockets[id] = new WebSocket(protocol + "://" + window.location.host + "/api/stream/" + id + "/data");
app.sockets[id].onopen = function(event) {
    console.log('websocket connected');
}
app.sockets[id].onmessage = function(event) {
  var msg = JSON.parse(event.data);
  if (app.node_data[id][msg.channelName]) {
    app.node_data[id][msg.channelName].value = msg.value;
    app.node_data[id][msg.channelName].timestamp = moment.unix(msg.timestamp).format('YYYY-MM-DDTHH:mm:ssZ');
  }

  app.update();
}
app.sockets[id].onclose = function(event) {
  console.log('close', event);
  app.socketInits[id]();
}
app.sockets[id].onerror = function(event) {
  console.log('error', event);
  app.socketInits[id]();
}
```

Happens on all tenants I've tested so far 316 and 101204. It works as intended on other browsers.

**Comment by Ashtonian** [comment]
IE11 blocks web socket connections to localhost by default. Try adjusting the security settings for intranet sites: https://github.com/qzind/qz-print/issues/39#issue-87042860

**Comment by Ashtonian** [comment]
Possibly related: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12090409/

**Comment by Ashtonian** [comment]
@balintd  did that work ? can we close this ?

**Comment by balintd** [comment]
Thanks for the info! I'll need to do more research on it but I don't need the issue for it.

**Comment by Ashtonian** [comment]
@balintd thanks
