### ISSUE TITLE
Delete dialog has wrong object type

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#173]
Domain: hsbqa.carbon.meshify.com
Current Behavior:
When I went to delete a node, the confirmation dialog asked me to confirm deleting users
Expected Behavior: Should say node not users.
![image](https://user-images.githubusercontent.com/9382834/35159666-f2e2affe-fd08-11e7-83f9-f0065dbd90dc.png)

**Comment by NateDawg90** [comment]
Fixed and deployed on 1/26/18.
