### ISSUE TITLE
Feature: New API endpoint to add already existing user to another folder

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#181]
Folder A:
- User A
- User B

Folber B:
- User C
- User D

In the HSB Enrollment core, a user role called 'Location Manager' is creating users (notification contacts) in one of the Enrollment steps. It is possible that a Location Manager would like to add a user to her account who already exists in another account (that the Location Manager has no access to). When that happens, we receive the 'duplicate entity' error after trying to create a new user.

Would it be possible to provide an API endpoint which we can use, so that a Location Manager could add User C to Folder A, so that User C would be a part of both Folder A and B?

**Comment by decker405** [comment]
I recommend using the experimental query API. Give me today to update it a bit (breaking change). Give me until the end of the week to finalize the design. You can start using it today, but it may break throughout this week. Changes to come are listed here: https://github.com/meshifyiot/carbon/issues/423

`POST /api/users/query {"filters": [{ "fieldName": "email", "operator": "eq", "value": "email@email.com" }]}`

**Comment by balintd** [comment]
I should've pointed out better that the Location Manager in this case most probably won't have access to the folder that the already existing user is in.

So based on the example above: User C wants to add User A to Folder B, while not having access to Folder A.

**Comment by decker405** [comment]
Unfortunately that would break our security model, so we can't allow that. A user can't add an existing user they can't view or edit to a new folder, because that would allow them to edit that user.

**Comment by psk788** [comment]
But in this case the user would have no idea why he can't add someone to a folder. As far as he knows he's adding a new user to his folder (since he can't see that the user already exists).  Shouldn't there be some way to accommodate this?

**Comment by balintd** [comment]
@psk788 We get a 'duplicate entity' error back on user creation. In the HSB Enrollment core at least we have an alternate workflow to let the user know about it and ask them to contact MSC. It hasn't been implemented yet but will be (since we won't be able to add the already existing user).

**Comment by willpopski** [comment]
Yeah this is where our security model fails. We combined user ownership with user access.

Said another way, it should be easy to grant a user access to my stuff, regardless of what else they have access to.

Combining **control of user (user ownership)** with **access of user (what the user can see)** into the same folder structure breaks this use case. And I'd say that granting access to a user without changing who can control that user is a generally needed use case. It would have been hard to predict this particular use case, but I think it is why ACL and RBAC are so popular.

**Comment by decker405** [comment]
You are correct @willpopski and we knew these limitations from the beginning, but accepted them for a speedier implementation. So, at this juncture, this is a limitation of the platform.

**Comment by willpopski** [comment]
Fair enough, but you guys didn't think through multi account users without Admin interactions. What's the solution to that?

**Comment by decker405** [comment]
At some point, you guys are going to have to accept the limitations of the platform and work around them. We are going to miss things, and there are going to be design limitations of the platform. 

I would love to be able to give y'all the world, but the requests for changes are getting out of hand, and we have absolutely no time to work on this right now. Y'all are going to have to figure out a clever solution for yourselves this time. We can consider deeper access control mechanism at a later date.

**Comment by willpopski** [comment]
This is getting way off topic. If you have a problem with requests, then let's follow up elsewhere.
