### ISSUE TITLE
Documentation for deployment

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#182]
The core I've been working on is on its own branch and I've been using an old version of deploy.js to deploy to different tenants. I saw that it changed lot, but I'd rather not experiment with it. 

Would it be possible to have documentation for all the different commands, parameters we can use for deployment now?

**Comment by decker405** [comment]
It's documented fairly comprehensively in the readme in the root of the applications repo (https://github.com/meshifyiot/applications). Send me a message on Slack if you have any other questions.

**Comment by balintd** [comment]
Ah, forgot to check there, thank you!
