### ISSUE TITLE
Admin: Send Invitation Email produces red banner, then green banner, but still doesn't send

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#183]
Steps to reproduce:

mirion.carbon.meshify.com
support@meshify.com

Go to Admin
Go to Users
Go to matthew@meshify.com
Click Send Invitation Email
Click Yes on Modal

See red banner "Unable to Send Invitation Email"

Again, click Send Invitation Email and confirm Yes
See green confirmed banner this time, but no e-mail is sent.

After waiting 2 minutes, I still don't have an e-mail invitation.

**Comment by willpopski** [comment]
![image](https://user-images.githubusercontent.com/116724/35305325-934a81f8-005e-11e8-94fa-4de0a01c009c.png)

**Comment by decker405** [comment]
Fixed. Rare deploy snafu.
