### ISSUE TITLE
Dashboard3: When user tries to login and is stuck at "Loading" due to 403 Forbidden, show meaningful message

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#184]
mirion.carbon.meshify.com
logged in as support@meshify.com
IMPERSONATING matthew@meshify.com (end customer role)

Created "End Customer" role which does NOT have permissions to:

Read Users
Read Rules

Observed results:

Stuck on Loading Dashboard
![image](https://user-images.githubusercontent.com/116724/35305623-9e750a48-005f-11e8-9446-dbe707c2a92a.png)

Console shows 403 (Forbidden) for those read items.

![image](https://user-images.githubusercontent.com/116724/35305652-bfe6617c-005f-11e8-8b9f-079b115f29b6.png)

**Expected Behavior**

If a user doesn't have credentials to log in, then the page should indicate such.
For example "Error: User account does not have permissions to access this page"
We may want to remove the "Loading..." verb since it is no longer loading (unless it is otherwise very obvious).

Also, just a side note, I might use blue for the loading color until something goes bad, and switch to orange/red when something goes bad.

**Comment by decker405** [comment]
Will do, I'll see if we can get to it this sprint.

**Comment by willpopski** [comment]
Is it odd that reading Rules and Users block loading of D3?

**Comment by decker405** [comment]
It's not odd that it _did_ happened, but I agree that it's not something that should happen. We'll figure it out and get it fixed. The dashboard should with incomplete information, until we just show a "no access" information because there is no reason to show the dashboard or something.

**Comment by willpopski** [comment]
Yeah, I think you're spot on with that. If no User read access, then hide the User icon on left.

**Comment by NateDawg90** [comment]
@willpopski I'm not seeing this issue anymore. I'm able to log in with a user who can't read users or rules and D3 isn't hanging up at the loading bar screen. Let me know if it is persisting for you

**Comment by NateDawg90** [comment]
Fixed.....sometime in the past.
