### ISSUE TITLE
Visiting new core results in 404

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#186]
Domain: hsbdev.carbon.meshify.com
Core: https://hsbdev.carbon.meshify.com/admin#cores/edit/13
Application: https://hsbdev.carbon.meshify.com/admin#applications/edit/75

On visiting hsbdev.carbon.meshify.com/fulfillment I get 404, even though all the files are deployed correctly it seems and the core works perfectly on local (starting it up with the same domain). I went through all the configurations, build.json and compared them to other cores, everything seems to be set up correctly for me.

Source code for the new fulfillment core is in the `hsb-cores` branch.

**Comment by decker405** [comment]
You haven't added the fulfillment application to the domain `hsbdev.carbon.meshify.com` in the Domains screen.

**Comment by balintd** [comment]
Ah, thanks, I forgot about that setting.
