### ISSUE TITLE
Core Deployment: Ability to use environment/coreId pairs

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#187]
In `build.json` right now, we have the option to define different environments/domains to deploy cores to, but we can only define one `coreId`.

For HSB we have multiple tenants and multiple domains per tenants in most cases. `coreId` for the `enrollment` core is different between tenants so I'm suggesting environment details instead of this:
```
"domains": {
    "hsbqa": "https://hsbqa.carbon.meshify.com",
    "hsbpreprod": "https://hsbpreprod.carbon.meshify.com"
 },
 "coreId": 12,
```

to look more like this:
```
"environments": {
    "hsbqa": {
      "domain": "https://hsbqa.carbon.meshify.com",
      "coreId": 12
    },
    "hsbpreprod": {
      "domain": "https://hsbpreprod.carbon.meshify.com",
      "coreId": 14
    },
 },
```

**Comment by decker405** [comment]
I'll grab this, shouldn't be too difficult.

**Comment by decker405** [comment]
I just merged this into master.

- `environments` is renamed to `targets`
- `domain` is `url`
- `coreId` is now inside of each target block like you suggested

**Comment by balintd** [comment]
Awesome, thank you!
