### ISSUE TITLE
Can we prevent people from inadvertently overwriting non-text file types in the files section?

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#19]
from @willpopski.

Need more information on this one. Not entirely sure what you mean, or what the intended use-case is.

**Comment by willpopski** [comment]
In admin files, if I click on a pdf, add some text, and click save, it appears to replace the file with that text. So basically, we don’t want to use the text editor for non text files.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NateDawg90** [comment]
Merged and delpoyed. It now only allows editing for html, xml, js, py, txt, and css files. We can update as needed
