### ISSUE TITLE
Lambda getHistoryData example

### ISSUE THREAD

**Issue by hdaddeo** [meshifyiot/carbon-docs#193]
The example on how to use the getHistoryDataByUniqueId function lists "start time" as more recent than  "end time."

var start = Date.now() / 1000
var end = Date.now() / 1000 - daysToSeconds(900)

These should be reversed to match the function requirements.

var start = Date.now() / 1000 - daysToSeconds(900)
var end = Date.now() / 1000

**Comment by Ashtonian** [comment]
fixed, good find, thanks! If your feeling up for it in the future, pull requests with doc changes would be greatly appreciated.
