### ISSUE TITLE
Echo API endpoint

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#197]
**New feature:** A new endpoint specifically designed for people to test their access to the API and get a predictable response. This would be used for troubleshooting or debugging connectivity by new users getting started on the platform and potentially for basic API up pinging.

**Business need:** Provides usability enhancement for new users just starting to work with the Meshify Carbon API. It also provides a way to test connectivity to receive a predictable response.

**Comment by decker405** [comment]
This can be done currently by hitting /api/users/me using Basic Authentication. A 200 response with your user information will inform you of:

- the API being up
- the API working
- your user being set up correctly

**Comment by Ashtonian** [comment]
`api/health` is an unauthenticated 200 empty response if you'd like to see that you are able to talk to the api.
