### ISSUE TITLE
Consolidated Notifications UI

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#20]
From Matt P:

> We've discussed this, but it would be helpful to have a consolidated Notifications UI.. doesn't have to be exactly like legacy, but just an easier way of building an alarm+reaction

@willpopski : would be nice to have a lengthier description of the pain points and what would be helpful.

**Comment by willpopski** [comment]
Main Pain Points:
- Have to switch between multiple admin sections to complete a notification (rule, reaction, subscription). In particular, switching the sections, means you have find the rule on the reaction dropdown list.
- Naming the rule and reaction creates extra work and cognitive overhead
- The same applies to extends to the subscription phase

Proposed approach:
- For a consolidated alarm creation UI, I'd let people do it on one page without switching tabs. There may be sections that shrink down to 'get out of the way' to keep it from looking overwhelming. The code could assume a 1:1:1 between rule, reaction, and subscription. It would also be very nice to see all users that are subscribed to the rule without having to switch sections.

**Comment by decker405** [comment]
Moving to internal issue: meshifyiot/applications#95
