### ISSUE TITLE
Slow response time for making a request to api/folders

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#201]
Domain: hsbpreprod-democlientcompany.carbon.meshify.com (but I experience the same thing with the same request, same core, etc on different tenants as well)

API request: /api/folders

Authenticated user's id: 2526

Response: 
```
[
   {
      "createdAt":"2018-02-02T14:42:44.511Z",
      "id":5582,
      "information":{
         "address":{
            "address":"821 Oak St Apt 821",
            "code":"07304",
            "country":"USA",
            "locality":"JERSEY CITY",
            "region":"NJ"
         }
      },
      "location":{
         "lat":40.71783,
         "lng":-74.07292
      },
      "metadata":{
         "client_company_code":"9999",
         "folder_type":"Participant",
         "kit_no":"11",
         "program_code":"1100099",
         "user_defined_field_1":"Business Hours",
         "user_defined_field_2":"Test",
         "user_defined_field_3":"Test",
         "user_defined_field_4":"Test",
         "user_defined_field_5":"Test"
      },
      "name":"PerformanceAccount021",
      "parentFolderId":5386,
      "root":false,
      "tags":[

      ],
      "theme":{

      },
      "updatedAt":"2018-02-02T14:42:44.511Z",
      "usercount":1
   }
]
```

Screenshot of Chrome devtools Network tab
![image](https://user-images.githubusercontent.com/368531/37612756-6287139c-2ba6-11e8-99d0-52fd04360ec7.png)

Issue: response time for this API request seems to be around 5 seconds (sometimes a bit less, sometimes a bit more)

**Comment by Ashtonian** [comment]
I would recommend using the `folders/query` endpoint with paging for your UI. 

I have added a missing index and that seems to have cut response times in half. Making this endpoint go much faster is going to get expensive. I'd like to add some caching eventually but that will likely be a while.

**Comment by balintd** [comment]
Testing the same scenario, TTFB time went from 5s to below 600ms, that's a great improvement, thanks!
