### ISSUE TITLE
D3: User account pop down menu usability improvements

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#204]
![image](https://user-images.githubusercontent.com/116724/37792473-e1e8c222-2dd9-11e8-9c17-0f99754ca32e.png)

Recommended usability improvements:

- [ ]  Eliminate gap between menu and user name so that the two objects look more associated
- [ ]  Add shading so it looks like the menu is a separate object, hovering on the page
- [ ]  Make the menu go away when I click anywhere else on the page

**Comment by NateDawg90** [comment]
resolved and merged.
