### ISSUE TITLE
Folder information in email templates

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#206]
I was looking at the documentation for email templates and it seems like it would be possible to have folder related information in them. However I'm having trouble actually generating that information in the email, I've tried `{{ Folders[0].information.address.code }}` and `{{ Folders }}`. There weren't result in the emails.

I'd like to ask for clarification on the syntax and how to render folder information into the emails.

**Comment by Ashtonian** [comment]
please see https://github.com/meshifyiot/carbon-docs/issues/129#issuecomment-352135577 - let me know if you have any additional issues with it!
