### ISSUE TITLE
Invitation email is not being sent out when template includes folder data

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#208]
Domain: hsbdev.carbon.meshify.com
Logged in as user id 38.
I'm creating and revoking membership of user id 10315 to test invitation email.

If I have
`{{ Folders.0.Name }}`
or
```
{% with Folders|first as firstFolder %}
    {{ firstFolder.Name }}
{% endwith %} 
```

in the email template, the email is not being sent out. Once I remove folder variables from the email template and revoke -> create membership for the user again, the welcome email is sent out immediately.

**Comment by decker405** [comment]
`{{ Folders.Results.0.Name }}`

**Comment by Ashtonian** [comment]
we have a internal mapping issue with this, will fix and deploy shortly!
