### ISSUE TITLE
Admin: I can't save domains, 'Apps field is not valid' error

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#209]
Domain: https://hsbqa.carbon.meshify.com
Authenticated user: 1763
Browser: latest Chrome/Win10

I'm trying to edit domain theme and then save, but I get the following error:
`Apps field is not valid`

I get this error regardless of which domain I'm trying to edit in what way on this tenant. All the apps and cores are properly set up.

**Comment by Ashtonian** [comment]
@NateDawg90

**Comment by NateDawg90** [comment]
Quick find! Merged and deployed.

**Comment by balintd** [comment]
Thanks!
