### ISSUE TITLE
Refresh button sometimes loads empty node details

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#210]
Bug reported by HSB, Zendesk ticket #1044.

https://meshify.zendesk.com/agent/tickets/1044

**Comment by willpopski** [comment]
https://meshify.zendesk.com/agent/tickets/1044

**Comment by willpopski** [comment]
This is the same as: https://github.com/meshifyiot/applications/issues/342

**Comment by NateDawg90** [comment]
This was merged and deployed on 3/28/18.

**Comment by Gayle313** [comment]
This is still an issue when in Folder View,

**Comment by Gayle313** [comment]
Cleared my cache and used an incognito window.  Same result in Folders view.  (works in Users, Alarms, Nodes)  In Map view a pop up box comes up that says 'No results' with the map grayed out'

**Comment by willpopski** [comment]
@Gayle313 could you please include the exact steps you are taking to reproduce the issue. I'm not seeing it anymore but maybe on a specific domain with a specific series of clicks it is happening. Thanks.

**Comment by Gayle313** [comment]
Logged in to https://hsbqa.carbon.meshify.com/dashboard3#
navigate to Folders
Hit Refresh
Returns Blank Page
Navigate to Map
Hit Refresh
Returns grayed out map with white box stating 'No Results'
Logged in to https://hsbprod.carbon.meshify.com/dashboard3#
navigate to Folders
Hit Refresh
Returns Blank Page
Navigate to Map
Hit Refresh
Returns grayed out map with white box stating 'No Results'

**Comment by willpopski** [comment]
I was also able to reproduce this readily by reloading the following URL logged in as support@meshify.com (cache disabled):

https://carbon.meshify.com/dashboard3#folders

**Comment by NateDawg90** [comment]
The refresh button currently does not work in folders and map view. Currently working out the issue, hold tight...
