### ISSUE TITLE
Dashboard3 doesn't respect the logoUrl theme attribute

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#212]
Admin and Dashboard 1(2?) login page and upper left hand logo, all respect the logoUrl when applied to the Domain theme but Dashboard3 doesn't.  Can Dashboard3 have this feature so that HSB can created branded domain Dashboards

**Comment by willpopski** [comment]
@NateDawg90 pls ping me when this is in production so we can update the customer. thanks!
