### ISSUE TITLE
D3 - Clicking on Nodes sub-section actually opens Folders

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#214]
On carbon.meshify.com, logged in as support@meshify.com.

1. Load the page
2. Click directly to "Folders" section
3. Click "Nodes (12)" link

### Expected result:
Show nodes in that folder

### Actual result:
Just refreshes the Folders subsection

![image](https://user-images.githubusercontent.com/116724/38112442-8c6a0bd8-3367-11e8-8999-3b4ad023fccc.png)

**Comment by NateDawg90** [comment]
Merged and deployed with the updates last week.
