### ISSUE TITLE
BUG:  notificationschemas API gives duplicate entity error when trying to change name

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#217]
Domain: hsbdev.carbon.meshify.com
Reproduction steps:
1. Create a notification schema
2. Either update the schema in the UI or with a PUT request in Postman, changing just the name of the schema

Current Behavior: 400 Bad request - Duplicate Entity
Expected Behavior: The schema should update names and allow the change.

**Comment by willpopski** [comment]
@psk788 Can you please send payload.

**Comment by psk788** [comment]
Can't recreate anymore.  Gonna chock it up to user error on my part.
