### ISSUE TITLE
Bug: Dashboard3 does not render node type templates that have "-details" in the name

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#219]
Domain: hsbqa.carbon.meshify.com
Reproduction steps:
1. Create a new node type template with the format "{nodetype}-details"
2. Open the dashboard3
3. Observe missing tab
--------------------------------------------------
Dashboard3 view (missing details tab):
![image](https://user-images.githubusercontent.com/9382834/38365811-bceda0d2-38ab-11e8-94d5-452ace04c933.png)
--------------------------------------------------
Dashboard view (shows details tab):
![image](https://user-images.githubusercontent.com/9382834/38365834-d1d7d1f2-38ab-11e8-9299-a7f0463ae1f2.png)
--------------------------------------------------
Expected Behavior: All tags should be rendered as expected regardless of name or some sort of validation should be done to prevent reserved words from being used.

**Comment by NateDawg90** [comment]
merged and deployed...sometime in the week of 4/1/18
