### ISSUE TITLE
Admin: Revisit UX for the 'create users' UI flow

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#221]
In the create users flow, we've run into usability issues. This flow is used early in a customer's experience and contributes to the first impression and therefore, we should nail it.

Consider the following 'types' of users that customers will create, specifically for the Admin UI:

### Normal users
Get invitation e-mail immediately so they can log in
Importance and frequency of use case: ✅✅✅✅✅

### Delayed normal user
Create user with e-mail address as above, but don't send invitation e-mail yet
Importance and frequency of use case: ✅ (pretty rare)

### Notification only user
Create user, but they won't have an e-mail, just phone number
Importance and frequency of use case: ✅ (pretty rare)

So, based on that, I'd say the "happy path" is to make a normal user and send invitation e-mail immediately.

Here is a mockup based on expected usage patterns:

https://app.moqups.com/mattmeshify/SwllwHT97X/edit/page/aa9df7b72

**Comment by willpopski** [comment]
Per our discussion:

- I'd recommend adding validation on "Save and Invite" instead of disabling until e-mail is added since it's not communicated to the user why it doesn't work. Providing field highlight and validation message would be consistent with the rest of the form's validation behavior
- You may want to consider moving "First Name" "Last Name" and "E-mail" (in that order) to the top of the form since those are most important
- We should probably remove the "(Optional)" text from the information section since it breaks convention. You had a cool idea of having a collapsable section for information as well.

**Comment by NateDawg90** [comment]
All of that is easily doable except the last bullet point. That would require changing our validation to include messages. Right now, it just runs through each field and checks a function that returns false if the criteria isn't met. There's no feedback to the user on why it failed, only "FIELD field isn't valid". So that's a larger question.

**Comment by willpopski** [comment]
Okay. About that last one, I thought you did a project to add meaningful error messages.

**Comment by NateDawg90** [comment]
Those were server error messages. The validation messages are a different animal. I would have to add a message string to what the validation functions return.
