### ISSUE TITLE
Trying to update .html file in Admin/Files section's code editor results in error

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#231]
Domain: hsbqa.carbon.meshify.com
User Id: 1736
File: https://hsbqa.carbon.meshify.com/api/files/public/setseg/school/support.html

Opening it, making edits than saving results in the following error:
`There is another file with that name already.`

**Comment by Ashtonian** [comment]
@NateDawg90 - this is likely a UI issue can you look into it?

**Comment by NateDawg90** [comment]
Gotch, yeah. It looks like the list isn't allowing updates on html files. Checking it out
