### ISSUE TITLE
Admin Files: Hitting 'Upload X Files' button only seem to upload Math.round(X/2) number of files, not all the files

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#233]
Tenant: experienced it on all HSB tenants, for example hsbqa.carbon.meshify.com
User Id: 1736

Example scenario:
- I drag and drop 10 files into the 'Upload Files' gray box
- I click the button 'Upload 10 Files'
- 5 files get uploaded, other 5 remains in drag and drop gray box
- Now I click 'Upload 5 Files'
- 3 files get uploaded, 2 remains
- Now I click 'Upload 2 Files'
- 1 file get uploaded, one remains
- I click 'Upload 1 File'
- Last file gets uploaded as well

If I wait for the green 'Files uploaded' message after clicking the Upload button again, there are no errors showing up at all and eventually all files get uploaded correctly. 
I had to upload the same 10 files to 5 tenants and the exact scenario above went down all 5 times.
Same issue seems to be in both Private and Public file uploader.

**Comment by NateDawg90** [comment]
merged and deployed on 5/1/18.
