### ISSUE TITLE
Quick Search Freeze after reviewing Contacts on Attributes Node

### ISSUE THREAD

**Issue by Gayle313** [meshifyiot/carbon-docs#238]
TThere is a bug in Dashboard while using the Quick Search:

Scenario:  Search for an Account, Select the Account, Navigate to the attributes Node, Click on Contacts
Expected Result:  Contacts are shown and Quick Search remains an active field and the user can remove previously entered search criteria
Result:  Quick Search freezes and holds the previous search criteria and grays out the Quick Search area
Work Around:  Navigate to Folders, Users, Nodes, Advanced Search, Select F5 to refresh the screen.

**Comment by Jmatos87** [comment]
We have looked into this issue and have found what the source may be. Looks like it is a template issue (attributes-contacts).

`updateElementsByTag("input", "disabled", true);`

This is the culprit. Going to ping @psk788 with a possible solution.

**Comment by psk788** [comment]
Thanks @Jmatos87 !  I've fixed this issue by removing that line as it was unnecessary.
