### ISSUE TITLE
Admin folders search - treats search criteria as contiguous string

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#24]
I'm looking for a folder called:

First Baptist 01234

I would like to use the search term "First 01234" to find this folder.

Currently when I search for "First 01234", I don't get a response.

LateOct2017

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/27/17.

**Comment by willpopski** [comment]
@MattMadeiro thx, works like a charm.
