### ISSUE TITLE
On Admin, Users -> it is hard to find the assigned folder(s) on large folder lists

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#25]
It would be nice if the the checked items were bubbled up to the top.

![image](https://user-images.githubusercontent.com/116724/30918303-26d757de-a36c-11e7-971d-d800ff6b2e97.png)

**Comment by NateDawg90** [comment]
- Items that are selected will now bubble up to the top on page load. If they are unchecked and then saved, they will revert to their original positions.

Merged and deployed on 10/3/17

**Comment by willpopski** [comment]
Tested and looks great!
