### ISSUE TITLE
Provide additional context to notifications in Reactions

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#26]
Business Rationale: The notifications requested by HSB have node/folder specific details that must be provided by the node triggering the notification.  I.E. the location of the node would be displayed in the email.  Right now the context is limited.  

Desired Outcome: Can most of the data that is included in the UI, be included in the Reaction context.

More specifically the following Node information 
vanity name, 
channel data, 
nodetype information, 
alarms, 
metadata, 
location, 
parent unique id/vanity name

**Comment by Ashtonian** [comment]
After talking with @psk788 a bit about this additional functions to grab node(s) by specific info would be nice. 

* GetByFolder
* GetByTag
* GetByMetaDataContains ?

**Comment by Ashtonian** [comment]
Add theme related functions context(s)

**Comment by psk788** [comment]
Any theme related properties would also be nice to have in the context but not as important as the actual details/metadata.

**Comment by Ashtonian** [comment]
Requirements - add following to reaction context: 
-[ ] vanity name/node info 
-[ ] nodetype information 
-[ ] folder information including metadata/ theme 
-[ ] parent node information

Hey @psk788  - what did you mean specificially with these two? current channel data / current alarms?  
-[ ] channel data 
-[ ] alarms

**Comment by psk788** [comment]
Channel data would be current channel value, timestamp, and vanity name
Alarms would just be the current active alarm names on a node. It's not necessary at the moment but figured if it could be tossed in, why not.

**Comment by Ashtonian** [comment]
see https://github.com/meshifyiot/carbon-docs/blob/master/concepts/reactions.md for updated context and examples
