### ISSUE TITLE
'information' data missing from user object when received from the 'api/login' endpoint

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#27]
Description: I have an issue with the `api/login` endpoint. It responds with the user object on successful login, but for some reason the `information` property is null, even though it has data in it for sure. The response from `api/users/me` and `api/users` includes the `information` data.

Domain: hsb-carbon.meshify.com
User ID: 316

**Comment by Ashtonian** [comment]
fixed with https://github.com/meshifyiot/carbon/pull/226  

Deployed - @balintd confirm and close.

**Comment by balintd** [comment]
Fixed, thank you.
