### ISSUE TITLE
On Admin -> Users, cannot create a new user with empty e-mail

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#28]
Expected: Per the 1.0 release notes, an e-mail address is not longer required for user.

Observed: The Admin create User UI validation is not reflecting this. Also, the e-mail field appears in a section named "Required".

![image](https://user-images.githubusercontent.com/116724/30945230-1d077446-a3cb-11e7-8dab-e477d1361e67.png)

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/28/17. The 'email' field has been moved to the 'Optional' section of the form. 

Further changes:
- You can't send an invitation email unless the user has an email address.
- When sending the email or revoking membership, the form will automatically update to reflect this change.
- Additional notifications will appear to confirm the revoke or successful email sending.
- If you try to create a user with an email address already in the system, you'll receive a red alert notification explaining that duplicate email addresses are not allowed.
