### ISSUE TITLE
Folder 'information' properties are empty

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#29]
Domain: hsb-carbon.meshify.com
Example folder ID: 3661

Yesterday, the folders that are relevant to my work had populated properties under 'information'. Today all properties (address, code, country etc.) are empty on the same folders. This happens on GET request to 'api/folders' authenticated with our 'support@meshify.com' user

**Comment by Ashtonian** [comment]
good find - the list view was showing the same address for all tenants and it was the last one in the list - pointers are fun. Merged https://github.com/meshifyiot/carbon/pull/235 and deployed.
