### ISSUE TITLE
"Allowed role" defaults to inclusive, and provides no way apply fully exclusive access.

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#30]
If I want a user to have access to none of the existing Node Types, for example, I cannot apply this setting. I have to create a dummy "None" node type, and select that, in order to deselect all of the others. The UI is also not intuitive when none are selected.

**Comment by decker405** [comment]
Why do you want a user to have access to none of the existing Node Types?

In regards to your last sentence, Matt is working on #18

**Comment by decker405** [comment]
We're closing this for now because of the new UI changes in meshifyiot/applications/pull/87 – if the pain point is still there in a few weeks, we'll take another look.
