### ISSUE TITLE
UI Validation doesn't catch Node Type creating error

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#31]
The "No Selection" on create node type causes API error, but UI doesn't tell me anything.

See pic for setup.

API Response (looking at chrome dev tools):
{"id":"2cd9lIeM","code":"bad_request","status":400,"detail":"[Q8Z8wxLF] 400 invalid_request: response.driverId must be greater than or equal to 1 but got value 0, attribute: response.driverId, value: 0, comp: greater than or equal to, expected: 1"}

Pic: No UI validation and the API error response is not conveyed to user.

![image](https://user-images.githubusercontent.com/116724/30976151-0f810dba-a442-11e7-90fa-65013448aa61.png)

**Comment by Ashtonian** [comment]
I broke this by getting a bit overzealous with api input validation, it's a special case I overlooked. Fixed and deployed with  https://github.com/meshifyiot/carbon/commit/dd7c81ed48b306b64d1f583d7d30a5ae191c949c. 

@willpopski please verify and close.
