### ISSUE TITLE
Cron and Debounce should not be mandatory to create a rule 

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#32]
It is requiring cron and debounce on the Rules tab before I can create a new rule but should not be required or should default to a value.

![image](https://user-images.githubusercontent.com/9382834/30983552-bbc4399c-a458-11e7-8143-473fb38a2211.png)

**Comment by Ashtonian** [comment]
I verified this is good for the api - this is indeed a UI issue. The backend defaults to 0 - the front end probably should as well? passing it on.

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/28/17. Both cron and debounce default to 0 when creating a new rule, so you shouldn't run into any validation errors.
