### ISSUE TITLE
Dashboard template tab title doesn't handle Node Types with "-" in the name correctly

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#34]
http://qed-carbon.meshify.com/dashboard/#/folder/3520/node/7319

Expected: Expect to see the template Title appear in title, which is "LoRaWAN" (or template Vanity Name).

Observed: Half the node type name showed up. (My naive guess is that you're parsing for the first dash in the tag name, not the last dash.)

![image](https://user-images.githubusercontent.com/116724/30984517-884ac72c-a45b-11e7-8f00-824edd97f810.png)

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/28/17.

We'll use the template's vanity name if it's available, or the standard (tag) name if it's not. This will require some work to go in and add vanity names for all templates that do not have them.
