### ISSUE TITLE
The Parent Node and Parent Folder configuration is confusing

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#36]
The default value of "No Selection" fails for both of these fields. Since the Auto-Activation section will not be applicable much of the time, I'd recommend we hide the entire auto-activation section unless user specifically goes there.

![image](https://user-images.githubusercontent.com/116724/30985826-89d4b2ac-a45f-11e7-9c98-0a7e6e14eb95.png)

**Comment by Ashtonian** [comment]
these are defaulted in the API to `parent`

**Comment by NateDawg90** [comment]
Merged and deployed on 10/4/17.

Now, both of these boxes will default to 'parent', as does the API.
