### ISSUE TITLE
E-mail template documentation on admin UI

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#39]
The user probably needs to know:

-> What triggers each of the templates
-> What variables and template syntax is required
-> Whether or not HTML, markdown, or similar is supported

**Comment by decker405** [comment]
https://github.com/meshifyiot/carbon-docs/blob/master/concepts/emailtemplates.md

**Comment by NateDawg90** [comment]
Would you propose having a tooltip linking to the doc page, Will?

**Comment by decker405** [comment]
Matt and I are working on updated forms pages that will include descriptions of all the entities, so we may include it there.
