### ISSUE TITLE
Mobile Pagination

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#4]
On mobile (admin), is it possible to reduce pagination count for nodes, folders, etc?

**Comment by decker405** [comment]
Not sure I understand — basically, on mobile, increase the number of items per page, so you have less pages to move through overall?

**Comment by willpopski** [comment]
To clarify, the recommendation is to reduce the number of items per page. Right now, it shows 50 items on mobile, which makes a very long list.

**Comment by MattMadeiro** [comment]
Fixed and deployed on 9/28/17. On mobile devices, the page count is reduced to 20.
