### ISSUE TITLE
'folder access is not allowed' error on POST to 'api/publish/cloud'

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#44]
Domain: hsb-carbon.meshify.com
Example folder id: 3649
Logged in user ID: 353
Role ID: 15
Error message: 'folder access is not allowed'
Request: POST, 'api/publish/cloud'
Payload:
```
{"channelName":"weatheruid","nodeId":7295,"value":"w3659"}
```

User is logged in via user tokens.

The role has read/write permissions for folders.

**Comment by NateDawg90** [comment]
Does the role have 'publish cloud' permission?

**Comment by balintd** [comment]
Yes, it does.

**Comment by Ashtonian** [comment]
This is caused by the user not having access to the parent node's folder. 

PID = 3649 whose folder ID is 3659. It's very odd to me that we happened upon a case where the PID and folder ID are the same?

**Comment by balintd** [comment]
I think the issue was on my end. I was logged in with a user who had access to multiple folders and I wasn't filtering the nodes I received from the API based on current folder. 

I started filtering out nodes and only publish the message on the ones that are in the folder the user is currently operating in.

I don't fully understand how that fixed the issue, but it did, cloud publish works now on multiple accounts.

**Comment by Ashtonian** [comment]
the user requires access to the folder that the node is in so if the user is in that folder it has access to that folder and I believe all the child folders for that folder.
