### ISSUE TITLE
'api/theme' not returning theme from folder, only from domain

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#46]
User ID: 361
Folder ID: 3647
Domain: hsb-carbon.meshify.com

Both the domain and a parent folder of this folder have theme objects, with one property 'FAQPage', but different values.

I'm making a GET request to `api/theme` while being logged in with user 361, who has access to the folder. The response contains the theme object from the domain and not from the parent folder of the folder that the currently logged in user is in.

Should I be receiving the theme object from the folder?

(I also added the theme to the lowest level folder the user is in, request to `api/theme` still returned the theme object from the domain)

**Comment by Ashtonian** [comment]
I don't think it should be showing the theme object from the folder, that can be accessed via the get `folder/{id}`. But I could be wrong, not sure I fully understand the intent of the theme object yet, will talk to will when he returns on Monday about it.

**Comment by Ashtonian** [comment]
after talking to will this endpoint is supposed to "aggregate" with the lower levels all the folders and potentially the users theme object into one. This is indeed a bug. I won't be able to get to it until Wednesday unfortunately.

**Comment by balintd** [comment]
Thanks, it's not urgent for me. In my situation I have to call the api for the folders anyway, so I was able to make a quick workaround.

**Comment by balintd** [comment]
Thanks!

**Comment by balintd** [comment]
User ID: 407
Domain: hsb-test-carbon.meshify.com
Folder the user is in: 3674

When authenticated with this user and requesting theme from `api/theme`, I still get an empty object. The parent of the parent folder of 3674 (id 3672) has a theme object with two properties.

**Comment by decker405** [comment]
That is because we didn't actually deploy it! Had some deploy issue yesterday and apparently it got rolled back to the previous version. Should be good now. Just checked with that user.

**Comment by balintd** [comment]
Thank you!
