### ISSUE TITLE
Help on password reset email

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#48]
I'd like to modify the password reset email template to link to a page in the HSB Enrollment core.

The email template on hsb-test-carbon.meshify.com is currently empty. I'm not sure how to make sure the URL is displayed in the email with a token in it, that I can use in the app to change the user's password.

**Comment by decker405** [comment]
@balintd: I just wrote up the docs on email templates, take a look, and then let me know if you need more information: https://github.com/meshifyiot/carbon-docs/blob/master/concepts/emailtemplates.md

What you need to do in your situation is build the URL yourself using the provided `.Token` field. I may need to give you access to the domain in the context though, it's not currently there. Let me know.

**Comment by decker405** [comment]
meshifyiot/carbon#258 is deployed and gives you the Protocol and Domain to work with. You should be able to construct your own URL. Reopen this issue if you need more help.

**Comment by balintd** [comment]
Great, thank you!
