### ISSUE TITLE
404 on PUT request to '/api/passwords/changepasswordwithtoken'

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#51]
Domain: https://hsb-test-carbon.meshify.com
Request: 
```
fetch('/api/passwords/changepasswordwithtoken', {
  method: 'PUT',
  body: JSON.stringify(payload),
  credentials: 'same-origin'
})
```
Example payload: 
```
{"newPassword":"asdasdasd","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDc4MjAyMzEsInJpZCI6IjQ1MCJ9.dRz7JpfkbuCa9BxDRmskadkgNCsctN9svTkL8j2RtjA"}
```

**Comment by decker405** [comment]
You'll have to give me the actual token payload for me to debug this. The reason this 404 would happen is that somebody Invited the user and then revoked their membership before they attempted to set their password.

**Comment by balintd** [comment]
I think this related to me not setting membership correctly in the app. After I fixed that, password reset is working well. Thanks and sorry about that.
