### ISSUE TITLE
404 on GET request to '/api/authentication/membership?userId=' + id

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#52]
Domain: https://hsb-test-carbon.meshify.com
Request: 
```
fetch('/api/authentication/membership?userId=407', {
  method: 'GET',
  headers: app_tag.headers,
  credentials: 'same-origin'
 });
```
User role has permission to read memberships.

**Comment by decker405** [comment]
On first glance at the database it looks like that membership does not exist. So that's working as expected.

**Comment by balintd** [comment]
My bad, I didn't set the membership correctly.
