### ISSUE TITLE
Feature: make URLs case insensitive when navigating to application path

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#53]
For the record, the w3 standard is for domain names to be insensitive, but remainder of URLs to be case _sensitive_.
Source: https://www.w3.org/TR/WD-html40-970708/htmlweb.html

So, this isn't a bug. The app base path is 'enrollment'

This URL works:
http://selectivehouseofworship.meshify.com/enrollment

This URL doesn't work:
http://selectivehouseofworship.meshify.com/Enrollment

For branding purposes, users may use capitals and lower cases indiscriminately, without recognizing the implications of case sensitivity.

**Proposal:** Normalizing cases and making URL base path case insensitive.
**Justification:** Add flexibility for users to brand the url any way they want, for example by delineating words with case, e.g. iot.hsb.com/HouseOfWorship

**Comment by decker405** [comment]
Allegedly against HTTP spec, but Ashton wants to do it anyways.

## Requirements:

- [ ] make application path check use string.ToLower in not_found handler
- [ ] don't break case-sensitive S3 matching (actually not sure if it's case-sensitive)
- [ ] update Application handlers to lowercase path before inserting into database

**Comment by Ashtonian** [comment]
resolved with https://github.com/meshifyiot/carbon/pull/308
