### ISSUE TITLE
Cron and debounce are not documented in carbon-docs

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#55]
I searched the repo. Neither 'cron' nor 'debounce' returned a result. Just wanted to get something written down. Thanks!

**Comment by NateDawg90** [comment]
I added some (hopefully) helpful text in the rules page of the docs. Let me know if that's sufficient!

**Comment by decker405** [comment]
Link: https://github.com/meshifyiot/carbon-docs/blob/master/concepts/rules.md#cron--debounce-timers
