### ISSUE TITLE
Enhancement: impersonate user directly from folder view

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#56]
The folder view shows a list of users that are assigned to that folder. This request is to add the ability to impersonate directly from that list (so a small button to the right of the user). The justification is that it improves UX (it is a common workflow to go folder->impersonate somebody within that folder).

Otherwise, they have to go to the user page and search again.

**Comment by NateDawg90** [comment]
Merged and deployed #56 on Friday the 13th
