### ISSUE TITLE
Feature: For impersonation, a "return to self" button is needed rather than full logoff

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#57]
Currently, when impersonating, the only way to leave impersonation mode is to fully log off. This requires the user to log in again, which is disruptive to HSB's support center work flow. Would it be possible to swap the "log out" button for a "Return to self" or similar button in the Admin UI?

**Comment by decker405** [comment]
We can work on this.

This will be a UI and a backend change:
- Carbon issue: https://github.com/meshifyiot/carbon/issues/273
- UI issue:

**Comment by psk788** [comment]
Also appears that if you are impersonating a root user from a non root user account, you are able to manipulate the root boolean on your original account.  Root probably shouldn't be editable if the person editing is impersonating.

**Comment by Ashtonian** [comment]
@NateDawg90 the backend is done for this so its good whenever you are ready.

**Comment by decker405** [comment]
Deployed in the UI from meshifyiot/applications#207
