### ISSUE TITLE
Channel drop down list not populated on Rules page

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#6]
Domain: hsb-carbon.meshify.com
Reproduction Steps: 
1. Log into the admin page.  
2. Create or open a rule
3. Select a node type
4. Try to select a channel value
Actual Behavior: No channels appear in the drop down
Expected Behavior: Channels should be selectable in the drop down.

<img width="694" alt="screen shot 2017-09-26 at 2 06 29 pm" src="https://user-images.githubusercontent.com/9382834/30876255-05fccb1e-a2c4-11e7-810d-693152c31dcf.png">

**Comment by NateDawg90** [comment]
Fixed and deployed on 9/26/17
