### ISSUE TITLE
Dashboard search doesn't return results as expected (doesn't break on space)

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#60]
**Observed**: Search for "Olive Church" doesn't return "Mount Olive Lutheran Church".

**Expected**: The space would separate the search terms, so "Olive Church" should return "Mount Olive Lutheran Church". This is how it works on Admin.

URL: hsb-carbon.meshify.com/dashboard
User: support@meshify.com

**Comment by MattMadeiro** [comment]
Fixed and deployed on FRIDAY THE 13TH. (10/13/17.)
