### ISSUE TITLE
Got 400 bad request on api/stream/id/data

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#61]
Using support@meshify.com to get the stream of a QED lora node id=7319

Request returns bad request. Same on postman.

curl -X GET \
  http://qed-carbon.meshify.com/api/stream/7319/data \
  -H 'authorization: Basic c3VwcG9ydEBtZXNoaWZ5LmNvbTptZXNoaWZ5'

**Comment by decker405** [comment]
The stream API is for websocket connections, so you'll need to figure out how to do that with curl for this to work.

**Comment by willpopski** [comment]
Then the error message or documentation should explain that.

**Comment by decker405** [comment]
The documentation says: `Connect to the websocket data stream for a node`
