### ISSUE TITLE
Allow for custom password reset page.

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#65]
Currently, when creating the password reset email template, the URL variable resolves to a link and a token for resetting password. This doesn't allow separation of the token and the URL, for example, if we wanted to send users to a custom password reset page.

This feature would allow the 'reset email' to send the user to a themed password reset page rather than the URL that the variable passes.

**Comment by willpopski** [comment]
This would be used in mid-November if we want to add this feature.

**Comment by decker405** [comment]
This is currently doable. I added access to the .Domain, .Token, and .Proto fields for constructing your own URL in a recent ticket (#48). https://github.com/meshifyiot/carbon-docs/issues/48#issuecomment-335948655

Docs: https://github.com/meshifyiot/carbon-docs/blob/master/concepts/emailtemplates.md
