### ISSUE TITLE
404 on POST to 'api/publish/cloud'

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#69]
Domain: hsb-test-carbon.meshify.com
Request: POST, 'api/publish/cloud'
Payload:
```
{
   "channelName":"weatheruid",
   "nodeId":7369,
   "value":"mnt-99114542"
}
```
Error: 404

This request was successful before the recent API updates.

**Comment by psk788** [comment]
It looks like when the nodes were created in the test tenant, they were created with folderId as the parentNodeId so it was failing to find the parent when trying to publish. I'll speak to Al about fixing this on the batch enrollment.
