### ISSUE TITLE
Metadata and Theme Editor

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#7]
It is currently not possible to edit metadata in the UI at all.

It would be nice to at least have a raw JSON editor for:

- folders.metadata
- folders.theme
- nodes.metadata
- users.metadata
- domain.theme

**Comment by MattMadeiro** [comment]
A metadata editor has been deployed for folders, nodes, and users on 10/02/17. I'm holding off on the theme editor until we nail down exactly what it's supposed to do.

**Comment by decker405** [comment]
closing in favor of: meshifyiot/applications#89
