### ISSUE TITLE
Add highstocks chart to carbon

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#70]
**This is high priority, needed Tuesday Oct 24th to support the NOV pilot**

https://www.highcharts.com/stock/demo/compare

This is to simulate the customer application shown below. It requires two color coded axis and series.

![image](https://user-images.githubusercontent.com/116724/31745771-d6f02808-b429-11e7-8ed1-d3b5e812896c.png)

**Comment by MattMadeiro** [comment]
Added and deployed on 10/24/17. I'm writing up some documentation for the new feature.
