### ISSUE TITLE
Node Template Editor: Get channel list for selected device type

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#75]
During node template development, we frequently open another tab with channels to reference the available list of javascript variables that can be used, and specifically channel names.

This feature adds a list of channels for reference, visible when editing, and possibility the ability to insert the value by clicking (this is good for new users). The long term ideal would be intelligent completion during typing and syntax checking.

**Comment by decker405** [comment]
This is deployed. We also made it so you can copy the exact channel format to the clipboard by clicking a channel in the list (in supported browsers).
