### ISSUE TITLE
404 on `api/data/current`

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#76]
Domain: hsb-test-carbon.meshify.com
Request: `api/data/current?nodeId=7804&uniqueId=mnt-906245`

Venkat at HSB gets 404 for all the `api/data/current` requests the enrollment core is making, but those same exact requests are working perfectly for me. He sent me screenshots about request, do you see anything here that could cause the same request to get a 404 for him but not me?

![unnamed](https://user-images.githubusercontent.com/368531/32003218-b5bc4570-b99e-11e7-9a46-c4e5681690f6.png)
![unnamed 1](https://user-images.githubusercontent.com/368531/32003224-b802569e-b99e-11e7-8e37-da310376cf4c.png)

**Comment by decker405** [comment]
@balintd: A 404 is returned from that endpoint only when the node doesn't exist at all. Are you sure you have the correct id's?

Something odd: you're using both nodeId and uniqueId, you should really only be using one *or* the other, not both.

**Comment by balintd** [comment]
@decker405 I tried those exact same requests on my end, they have been working perfectly for me. Same account, same authentication, node ids, different results. I'll modify the request to only use one ID, maybe that'll make some difference.

**Comment by balintd** [comment]
@decker405 I removed the uniqueID, only using node id, same issue. Only on his environment (lastest Chrome, Windows 7, different network). It works perfectly for me.

**Comment by decker405** [comment]
@balintd: moving to Slack

**Comment by Ashtonian** [comment]
Check permissions

**Comment by balintd** [comment]
We're both authenticated with the same user, role 'Location Manager'.

**Comment by decker405** [comment]
@Ashtonian: @balintd and I have ruled out missing node, nodetype.AllowedRoles, correct domain, and folder visibility. He's using User Tokens, so I'm thinking that allowedNodeTypes isn't coming through in the SQL for some reason.

**Comment by Ashtonian** [comment]
`hsb-test-carbon.meshify.com/enrollment/api/data/current?nodeId=7804` which is not `hsb-test-carbon.meshify.com/api/data/current?nodeId=7804`

I was able to hit the endpoint with the user token creds locally and it worked. So I think its just a routing issue. 

closing for now - please reopen and bump it if there is still an issue.
