### ISSUE TITLE
Font on High Stocks charts does not match website font.

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#77]
Observed on qed-carbon.meshify.com.

![image](https://user-images.githubusercontent.com/116724/32064360-3028fc7c-ba3f-11e7-9437-a23091925225.png)

**Comment by willpopski** [comment]
Reopening. The font is still different. Observed on qed-carbon.meshify.com.

![image](https://user-images.githubusercontent.com/116724/32336296-e72cd2e0-bfbc-11e7-9632-f118b711474e.png)

**Comment by MattMadeiro** [comment]
We just changed our deploy process, and I think this was a holdover from when it wasn't working particularly well. Check again. The fonts should be updated.

**Comment by NateDawg90** [comment]
Closed.

**Comment by willpopski** [comment]
Yep, reloaded and it's a beaut! Thanks
