### ISSUE TITLE
Sample Template documentation is not working for me

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#78]
The code documented at link below does not produce the described output.

I think the <script> element needs to be inside of the tag itself. Even after moving it in, I'm getting blank values.

https://github.com/meshifyiot/carbon-docs/tree/master/cms/templates#sample-template

I got it to work by changing the order of channel_name and point in the `each` statement

```
<sample-template>

	<div each={ point, channel_name in opts.node.channels }>
		<h2>{ point.vanityName }</h2>
		<p>{ point.value }</p>
		<time>{ moment(point.timestamp).format('MMMM Do YYYY, h:mm:ss a') }</time>
	</div>

<script>
	var tag = this;
</script>

</sample-template>

```

**Comment by decker405** [comment]
Thanks. Updated it to be correct.
