### ISSUE TITLE
Users are receiving reactions for nodes in folders they don't have access to

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#80]
Domain: hsb-test-carbon.meshify.com
Reproduction Steps:
1. Create a user with folder access to a bottom level folder
2. Subscribe the user to a notification schema (i.e. battery alerts since it's something all nodes have)
3. Trigger a reaction from that schema on a node that is outside the only folder the user has access to.

Expected Behavior:
User should not get any notification since user does not have access to that node

Actual Behavior:
User is getting all reactions regardless of folder access.

**Comment by Ashtonian** [comment]
please re-verify, this was deployed a few hours ago. See #306
