### ISSUE TITLE
400 bad request on Lambda/Edit/Test

### ISSUE THREAD

**Issue by decker405** [meshifyiot/carbon-docs#82]
## Current Behavior

When a user tries to test a lambda and enters a string into the `value` field without quotes, the lambda shows `Loading...` indefinitely and there is a 400 bad request in the background.

There is a 400 bad request in the background because the test endpoint expects strings to have quotation marks around them.

## Desired Behavior

- If there is an error testing a lambda, a descriptive error message should display instead of `Loading...`
- If the user enters a string into the value box and there are no quotation marks, either display an error, or automatically add quotation marks before sending.

**Comment by NateDawg90** [comment]
Actually, the loading text says "Testing", not "Loading". Would you like it to say loading until the result is received from the API?

**Comment by NateDawg90** [comment]
Merged and Deployed on 11/3/17.
