### ISSUE TITLE
New tenant script: The Admin "allowed role" is set to all. It should only be set to Admin.

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#85]
Current: When the Admin roles is created with a new tenant, and a new role is added, this role is added as an Allowed Role, to modify Admin.

Expected: The only "allowed role" of Admin, by default, is Admin.

**Comment by decker405** [comment]
Done. Future tenants will be created with an admin role that is only allowed to be created by other admins.
