### ISSUE TITLE
Feature: Separate node type "Allowed Roles" by read an by write

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#86]
There are instances where a role with admin access should be able to view a node type, and access the admin core, but not write to the node type. For example, the HSB support center needs to have  access to the admin core, and needs to view all node types, but should not be able to edit node types.

cc: @psk788

**Comment by MattMadeiro** [comment]
We have Read & Wrote Node Type permissions available already. Are they not specific enough for this case? In your example, the HSB support center peeps need to view all node types, but not edit them. Wouldn't the existing permissions cover this?

**Comment by willpopski** [comment]
The case that prompted this issue where that specificity was needed: I wanted to create a role for training and new users in the same tenant where we were building their demo. So, for example, I wanted to give users the ability to create new node types, but not let them disrupt the ongoing Meshify work.

**Comment by decker405** [comment]
I'm going to close this for now as our current solution is to use different tenants. Work to remedy issues like this is moving towards multi-tenant management tooling (syncing node types, etc.)
