### ISSUE TITLE
Feature: Way to debug Rule debugging from Admin core

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#87]
Currently, I have no way to debug rules that aren't working as I expect.

For this, I would recommend that recent runs of the rule trigger logic are available in the UI showing the inputs and intermediary evaluations of the trigger logic. For example, for the Node Offline logic setup on NOV `channelCount('mono_sense_level',31) == 0`, I would want to know the last time that the rule ran and what the channelCount function evaluated to and if there were any errors.

**Comment by willpopski** [comment]
I can provide UI ideas if it would help.

**Comment by decker405** [comment]
We already have this in the current sprint: https://github.com/meshifyiot/applications/issues/108

I'm going to close this for now. If we still desire more insight after having the testing UI, we'll reopen this and discuss more.
