### ISSUE TITLE
Feature: When new role is created, make allowed roles equal to role of user that created the role

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#88]
Similar to #85, but applies to roles created from Admin console UI. Right now, the default is "all roles", which may inadvertently expose roles.

Recommendation is to make the 'allowed roles' equal only to the role of the logged in user rather than 'all users'.

Justification: Tyranny of the default. I don't think most users will change this, and it may inadvertently expose a role in unintended ways.

**Comment by decker405** [comment]
Deployed from meshifyiot/applications#209
