### ISSUE TITLE
Feature: Add way to navigate/browse folders in dashboard

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#90]
Current: The folders are flat and there's no way to see the hierarchy structure in the dashboard.

Concept: The first thing that comes to mind is treeview, but it doesn't need to be.

Use Case: Logged in user wants to view nodes from different folders. They will move through folders with context of the hierarchy, e.g. wanting to select a last folder in the tree. They also want to move 'up' or to siblings in the folder hierarchy. When they 'move' to a different folder, the assumption is that the folder list/node list (to the right) is filtered by the selection.

This is a high priority for end of November.

**Comment by MattMadeiro** [comment]
This is coming in the big revision of the dashboard, so I'll go ahead and close it. (We have an internal issue tracking the same thing.)
