### ISSUE TITLE
Admin UI: Subscription edit page should show user identification

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#91]
In the Subscription section of the Admin UI, you click on a user name to go to the subscription edit page. (https://carbon.meshify.com/admin#subscriptions/edit/2)

Currently, this page only shows the subscriptions without the user information. 

I would expect this page to show some user identification info so that the user is certain who's subscriptions they are modifying.

![image](https://user-images.githubusercontent.com/116724/32512836-50753474-c3c6-11e7-88f2-b06549a871be.png)

**Comment by NateDawg90** [comment]
Username doesn't exist, only email are basically one in the same, so I'll display email just as the Users edit page does.

**Comment by willpopski** [comment]
Yeah, just some form of identification. Thanks.

**Comment by NateDawg90** [comment]
Fixed and deployrd on 11/30/17.
