### ISSUE TITLE
Dashboard: Pressing Active Alarm Doesn't Refresh Results

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#92]
Domain: hsb-test-carbon.meshify.com
Current Behavior:  Clicking an active alarm appears to do nothing because it is selecting filter items in the bottom left which may or may not be on the screen
Desired Behavior: Give an indication that an alarm was selected (maybe highlight the box) then either auto refresh the filter results with the additional alarm filter or add a button that is near the alarms to update the result set.

![image](https://user-images.githubusercontent.com/9382834/32514140-161bc2b2-c3ca-11e7-9df0-05d4cb685383.png)

**Comment by decker405** [comment]
Done.
