### ISSUE TITLE
[D3] Feature: Add a alarm bar chart to the Dashboard overview's Active Alarms pane

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#93]
Current: The active alarms are shown with a numerical count. They are clickable, which drives the filter view.

Feature: Show a bar chart (in addition to?) the list of active alarms. It doesn't need to be clickable.

Justification: This provides a view at-a-glance for the status of alarms in the system that is more easily digested than a simple numerical list.

![image](https://user-images.githubusercontent.com/116724/32514495-26d8397c-c3cb-11e7-9f08-ca00b6721860.png)

**Comment by decker405** [comment]
We're going to work on this in Dashboard 3

**Comment by NateDawg90** [comment]
I'm going to go ahead and add a couple things:

- Move the bar chart above the alarms list
- Make a top rectangular section divided in two, showing X Alarms and X Nodes
- Make a Group By _ button to switch chart grouping by icon/color
