### ISSUE TITLE
Is it possible for a user to add another existing user to his folder?

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#94]
Folder A:
- Person A

Folder B:
- Person B

If Person A is logged in, is there any way for that user to add Person B to Folder A (so that user would be in both folders)? Without Person A having access to Folder B of course, so PUT request with an updated list of folder ids won't work.

**Comment by decker405** [comment]
No. Person A could 'create' Person B in Folder A (if they had create user permissions and the correct allowed roles), but can not move a Person they do not have access to into their Folder.
