### ISSUE TITLE
add documentation for mfy_pub_log 

### ISSUE THREAD

**Issue by Ashtonian** [meshifyiot/carbon-docs#95]
need to add docs for what mfy_pub_log is and how to read it
also need to document reserved channels - mfy_loc

**Comment by decker405** [comment]
@Ashtonian 

What is `mfy_pub_log`?

I've got docs for `mfy_f_loc` and `mfy_n_loc` [here](https://github.com/meshifyiot/carbon-docs/blob/master/concepts/mqtt.md).

**Comment by Ashtonian** [comment]
@decker405 
It looks like a built-in channel we write to based on MQTT set success - https://github.com/meshifyiot/carbon/blob/master/apps/publisher/publisher.go#L148 

Also looks like sets are running twice and then writing a failure to that channel.
