### ISSUE TITLE
Admin Rules: Channel Name DDL does not refresh immediately after selecting Node Type

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#97]
Domain: hsb-carbon.meshify.com
Current Behavior and Reproduction Steps:
1.  Create new rule
2. Select a node type
3. Try to select a channel and fail

Expected Behavior:  As soon as you select a node type, the channel name should reflect the selected node types channels

Work around: If you hit create rule, the validation will partial submit the page and the values will populate.

![image](https://user-images.githubusercontent.com/9382834/32786001-d64ca88e-c920-11e7-8d31-9ff142e1545e.png)

**Comment by NateDawg90** [comment]
Fixed and deployed on 11/16/17
